name: CD

on:
  release:
    types: 
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/ffavre31/intro-to-ci-cd-ffavre13:${{ github.ref_name }} .

      - name: Push Docker image
        run: docker push ghcr.io/ffavre31/intro-to-ci-cd-ffavre13:${{ github.ref_name }}

      - name: Build
        run: make release

      - name: Upload dummydb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/main
          asset_name: main
          asset_content_type: application/octet-stream

      - name: Upload LICENSE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./LICENSE
          asset_name: LICENSE
          asset_content_type: text/plain